export const GSDL_REQUEST = "GSDL_REQUEST";
export const GSDL_REQUEST_SUCCESS = "GSDL_REQUEST_SUCCESS";
//
// export const DEFINITION_REQUEST = "DEFINITION_REQUEST";
// export const DEFINITION_REQUEST_SUCCESS = "DEFINITION_REQUEST_SUCCESS";
//
// export const SHAPE_REQUEST = "SHAPE_REQUEST";
export const SHAPE_REQUEST_SUCCESS = "SHAPE_REQUEST_SUCCESS";
//
// export const STYLE_REQUEST = "STYLE_REQUEST";
export const STYLE_REQUEST_SUCCESS = "STYLE_REQUEST_SUCCESS";
//
// export const DIAGRAM_REQUEST = "DIAGRAM_REQUEST";
// export const DIAGRAM_REQUEST_SUCCESS = "DIAGRAM_REQUEST_SUCCESS";