name: Frontend

on:
  push:
    branches:
      - 425-github-actions
  pull_request:
    branches:
      - 425-github-actions

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
