name: Test Services
on: [push, pull_request]

jobs:
  job_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.0.1]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout yFiles
        uses: actions/checkout@v2
        with:
          repository: Zeta-Project/yFiles-for-html
          token: ${{secrets.TOKEN}}
          path: main1

      - name: Checkout yFiles
        uses: actions/checkout@v2
        with:
          repository: Zeta-Project/yFiles-dev-key
          token: ${{secrets.TOKEN}}
          path: main2

      - name: tests
        run: |
          ls -lah
          ls -lah main
          ls -lah main1
          ls -lah main2
      
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to Frontend and test app
        run: |
          cd frontend
          yarn install
          yarn build


  job_api:
    name: Test api backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: uses openjdk
        uses: olafurpg/setup-scala@v10
        with:
           java-version: openjdk@1.11
      - name: compile
        run: cd api && sbt "compile" "scalastyle"
      - name: coverage
        run: cd api && sbt coverage "test" "coverageReport"
      - name: coverage report
        run: cd api && bash <(curl -s https://codecov.io/bash)